// automatically generated by the FlatBuffers compiler, do not modify

package br.com.rbcti.publisher.common.messages.fbs;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class LoginResponseFbs extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static LoginResponseFbs getRootAsLoginResponseFbs(ByteBuffer _bb) { return getRootAsLoginResponseFbs(_bb, new LoginResponseFbs()); }
  public static LoginResponseFbs getRootAsLoginResponseFbs(ByteBuffer _bb, LoginResponseFbs obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public LoginResponseFbs __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public br.com.rbcti.publisher.common.messages.fbs.HeaderFbs header() { return header(new br.com.rbcti.publisher.common.messages.fbs.HeaderFbs()); }
  public br.com.rbcti.publisher.common.messages.fbs.HeaderFbs header(br.com.rbcti.publisher.common.messages.fbs.HeaderFbs obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public byte responseCode() { int o = __offset(6); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public String authenticationToken() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer authenticationTokenAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer authenticationTokenInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }

  public static int createLoginResponseFbs(FlatBufferBuilder builder,
      int headerOffset,
      byte responseCode,
      int authenticationTokenOffset) {
    builder.startTable(3);
    LoginResponseFbs.addAuthenticationToken(builder, authenticationTokenOffset);
    LoginResponseFbs.addHeader(builder, headerOffset);
    LoginResponseFbs.addResponseCode(builder, responseCode);
    return LoginResponseFbs.endLoginResponseFbs(builder);
  }

  public static void startLoginResponseFbs(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addHeader(FlatBufferBuilder builder, int headerOffset) { builder.addOffset(0, headerOffset, 0); }
  public static void addResponseCode(FlatBufferBuilder builder, byte responseCode) { builder.addByte(1, responseCode, 0); }
  public static void addAuthenticationToken(FlatBufferBuilder builder, int authenticationTokenOffset) { builder.addOffset(2, authenticationTokenOffset, 0); }
  public static int endLoginResponseFbs(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public LoginResponseFbs get(int j) { return get(new LoginResponseFbs(), j); }
    public LoginResponseFbs get(LoginResponseFbs obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

