// automatically generated by the FlatBuffers compiler, do not modify

package br.com.rbcti.publisher.common.messages.fbs;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class PostArticleResponseFbs extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static PostArticleResponseFbs getRootAsPostArticleResponseFbs(ByteBuffer _bb) { return getRootAsPostArticleResponseFbs(_bb, new PostArticleResponseFbs()); }
  public static PostArticleResponseFbs getRootAsPostArticleResponseFbs(ByteBuffer _bb, PostArticleResponseFbs obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public PostArticleResponseFbs __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public br.com.rbcti.publisher.common.messages.fbs.HeaderFbs header() { return header(new br.com.rbcti.publisher.common.messages.fbs.HeaderFbs()); }
  public br.com.rbcti.publisher.common.messages.fbs.HeaderFbs header(br.com.rbcti.publisher.common.messages.fbs.HeaderFbs obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public byte responseCode() { int o = __offset(6); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public String articleUuid() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer articleUuidAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer articleUuidInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }

  public static int createPostArticleResponseFbs(FlatBufferBuilder builder,
      int headerOffset,
      byte responseCode,
      int articleUuidOffset) {
    builder.startTable(3);
    PostArticleResponseFbs.addArticleUuid(builder, articleUuidOffset);
    PostArticleResponseFbs.addHeader(builder, headerOffset);
    PostArticleResponseFbs.addResponseCode(builder, responseCode);
    return PostArticleResponseFbs.endPostArticleResponseFbs(builder);
  }

  public static void startPostArticleResponseFbs(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addHeader(FlatBufferBuilder builder, int headerOffset) { builder.addOffset(0, headerOffset, 0); }
  public static void addResponseCode(FlatBufferBuilder builder, byte responseCode) { builder.addByte(1, responseCode, 0); }
  public static void addArticleUuid(FlatBufferBuilder builder, int articleUuidOffset) { builder.addOffset(2, articleUuidOffset, 0); }
  public static int endPostArticleResponseFbs(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public PostArticleResponseFbs get(int j) { return get(new PostArticleResponseFbs(), j); }
    public PostArticleResponseFbs get(PostArticleResponseFbs obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

