// automatically generated by the FlatBuffers compiler, do not modify

package br.com.rbcti.publisher.common.messages.fbs;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class PostArticleRequestFbs extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static PostArticleRequestFbs getRootAsPostArticleRequestFbs(ByteBuffer _bb) { return getRootAsPostArticleRequestFbs(_bb, new PostArticleRequestFbs()); }
  public static PostArticleRequestFbs getRootAsPostArticleRequestFbs(ByteBuffer _bb, PostArticleRequestFbs obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public PostArticleRequestFbs __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public br.com.rbcti.publisher.common.messages.fbs.HeaderFbs header() { return header(new br.com.rbcti.publisher.common.messages.fbs.HeaderFbs()); }
  public br.com.rbcti.publisher.common.messages.fbs.HeaderFbs header(br.com.rbcti.publisher.common.messages.fbs.HeaderFbs obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public String authenticationToken() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer authenticationTokenAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer authenticationTokenInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String subject() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer subjectAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer subjectInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public String article() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer articleAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer articleInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }
  public String tags(int j) { int o = __offset(12); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int tagsLength() { int o = __offset(12); return o != 0 ? __vector_len(o) : 0; }
  public StringVector tagsVector() { return tagsVector(new StringVector()); }
  public StringVector tagsVector(StringVector obj) { int o = __offset(12); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createPostArticleRequestFbs(FlatBufferBuilder builder,
      int headerOffset,
      int authenticationTokenOffset,
      int subjectOffset,
      int articleOffset,
      int tagsOffset) {
    builder.startTable(5);
    PostArticleRequestFbs.addTags(builder, tagsOffset);
    PostArticleRequestFbs.addArticle(builder, articleOffset);
    PostArticleRequestFbs.addSubject(builder, subjectOffset);
    PostArticleRequestFbs.addAuthenticationToken(builder, authenticationTokenOffset);
    PostArticleRequestFbs.addHeader(builder, headerOffset);
    return PostArticleRequestFbs.endPostArticleRequestFbs(builder);
  }

  public static void startPostArticleRequestFbs(FlatBufferBuilder builder) { builder.startTable(5); }
  public static void addHeader(FlatBufferBuilder builder, int headerOffset) { builder.addOffset(0, headerOffset, 0); }
  public static void addAuthenticationToken(FlatBufferBuilder builder, int authenticationTokenOffset) { builder.addOffset(1, authenticationTokenOffset, 0); }
  public static void addSubject(FlatBufferBuilder builder, int subjectOffset) { builder.addOffset(2, subjectOffset, 0); }
  public static void addArticle(FlatBufferBuilder builder, int articleOffset) { builder.addOffset(3, articleOffset, 0); }
  public static void addTags(FlatBufferBuilder builder, int tagsOffset) { builder.addOffset(4, tagsOffset, 0); }
  public static int createTagsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startTagsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endPostArticleRequestFbs(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public PostArticleRequestFbs get(int j) { return get(new PostArticleRequestFbs(), j); }
    public PostArticleRequestFbs get(PostArticleRequestFbs obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

