// automatically generated by the FlatBuffers compiler, do not modify

package br.com.rbcti.publisher.common.messages.fbs;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class ProtocolMessageFbs extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static ProtocolMessageFbs getRootAsProtocolMessageFbs(ByteBuffer _bb) { return getRootAsProtocolMessageFbs(_bb, new ProtocolMessageFbs()); }
  public static ProtocolMessageFbs getRootAsProtocolMessageFbs(ByteBuffer _bb, ProtocolMessageFbs obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ProtocolMessageFbs __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte messageType() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public Table message(Table obj) { int o = __offset(6); return o != 0 ? __union(obj, o + bb_pos) : null; }

  public static int createProtocolMessageFbs(FlatBufferBuilder builder,
      byte messageType,
      int messageOffset) {
    builder.startTable(2);
    ProtocolMessageFbs.addMessage(builder, messageOffset);
    ProtocolMessageFbs.addMessageType(builder, messageType);
    return ProtocolMessageFbs.endProtocolMessageFbs(builder);
  }

  public static void startProtocolMessageFbs(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addMessageType(FlatBufferBuilder builder, byte messageType) { builder.addByte(0, messageType, 0); }
  public static void addMessage(FlatBufferBuilder builder, int messageOffset) { builder.addOffset(1, messageOffset, 0); }
  public static int endProtocolMessageFbs(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishProtocolMessageFbsBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedProtocolMessageFbsBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ProtocolMessageFbs get(int j) { return get(new ProtocolMessageFbs(), j); }
    public ProtocolMessageFbs get(ProtocolMessageFbs obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

